apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-a
    version: v2
  name: ms-a
  namespace: default
spec:
  selector:
    matchLabels:
      app: ms-a
      version: v2
  template:
    metadata:
      labels:
        app: ms-a
        version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-b
    version: v2
  name: ms-b
  namespace: ms-b-ns
spec:
  selector:
    matchLabels:
      app: ms-b
      version: v2
  template:
    metadata:
      labels:
        app: ms-b
        version: v2
